/** Declaration file generated by dts-gen */

export class Client {
    constructor(sock: any);

    call(name: any, ...args: any[]): void;

    methods(fn: any): void;

}

export class Server {
    constructor(sock: any);

    expose(name: any, fn: any, ...args: any[]): void;

    methodDescriptions(): any;

    onmessage(msg: any, reply: any, ...args: any[]): any;

    respondWithMethods(reply: any): void;

}
