/** Declaration file generated by dts-gen */

declare namespace BaseSwim {
    interface Options extends swim.SwimOptions {

    }
    interface Peer {
        /**
         * in "{host}:{port}" format
         */
        id: string;
        meta: {
            ringname: string;
            client: boolean;
            [key: string]: any;
        }
        points?: number[];
    }
}

declare class BaseSwim {
    constructor(id: string, opts: BaseSwim.Options);
    constructor(opts: BaseSwim.Options);
    leave(): void;

    static EventType: {
        Change: string;
        Error: string;
        Ready: string;
        Update: string;
    };

    on(event: 'peerUp', listener: (peer:BaseSwim.Peer) => any):this;
    on(event: 'peerDown', listener: (peer:BaseSwim.Peer) => any):this;
}

declare module "baseswim" {
    export = BaseSwim;
}