/** Declaration file generated by dts-gen */
/// <reference path="swim.d.ts" />

declare class Hashring extends NodeJS.EventEmitter {
    protected swim: swim;
    constructor(opts: Hashring.Options);

    allocatedToMe(key: number | string): boolean;

    close(cb?: () => any): void;

    lookup(key: number | string): Hashring.Peer;

    /**
     * in fact this returns current peer info
     */
    mymeta(): Hashring.Peer;

    next(key: number | string, prev: any): Hashring.Peer | null;

    peers(includeMyself: boolean): Hashring.Peer[];
    /**
     * return id in current Peer, i.e. the host:port
     */
    whoami(): string;

    on(event: 'up', listener: () => any):this;

    on(event: 'peerUp', listener: (peer: Hashring.Peer) => any):this

    on(event: 'peerDown', listener: (peer: Hashring.Peer) => any):this

    on(event: 'move', listener: (event: Hashring.MoveEvent) => any):this

    on(event: 'steal', listener: (event: Hashring.StealEvent) => any):this

    on(event: 'error', listener: (error: Error) => any):this
}


declare namespace Hashring {
    interface Peer {
        /**
         * in "{host}:{port}" format
         */
        id: string;
        meta: {
            ringname: string;
            client: boolean;
            [key:string]:any;
        }
        points?: number[];
    }
    interface Options {
        ringname: string;
        replicaPoints: number;
        client: boolean;
        local: {
            meta: {
                ringname: string;
                client: boolean;
                [key: string]: any;
            }
        }
        meta: any /*{
            id: string;
            points: number;
            [key: string]: any;
        };*/
        hashFunc: Function
    }

    interface MoveEvent {
        start: number;
        end: number;
        to: string;
        path: string;
    }

    interface StealEvent {
        start: number;
        end: number;
        from: string;
    }
}


declare module "swim-hashring" {
    export = Hashring;
}
